/** @type {import('tailwindcss').Config} */
module.exports = {
	darkMode: "class",
	content: [
		"./src/**/*.{js,ts,jsx,tsx}",
		"./src/components/**/*.{js,ts,jsx,tsx}",
		"./src/app/**/*.{js,ts,jsx,tsx}",
	],
	theme: {
		extend: {
			colors: {
				primary: {
					100: `#FFFFFF`,
					200: `#F4F4F4`,
					300: `#E9E9E9`,
					400: `#757575`,
					500: `#3A3A3A`,
					600: `#2D2D2D`,
					700: `#1F1F1F`,
					800: `#050505`,
				},
				secondary: {
					100: `#A445ED`,
				},
				error: {
					100: `#FF5252`,
				},
			},
			fontFamily: {
				mono: ["inconsolata", "mono"],
				serif: ["lora", "serif"],
				serifitalic: ["loraItalic", "serif"],
				sans: ["inter", "sans"],
			},
			fontSize: {
				"heading-l-sans": ["6.4rem", { lineHeight: "7.7rem" }],
				"heading-l-serif": ["6.4rem", { lineHeight: "8.2rem" }],
				"heading-l-mono": ["6.4rem", { lineHeight: "6.7rem" }],
				"heading-l-mobile-sans": ["3.2rem", { lineHeight: "3.9rem" }],
				"heading-l-mobile-serif": ["3.2rem", { lineHeight: "4.1rem" }],
				"heading-l-mobile-mono": ["3.2rem", { lineHeight: "3.4rem" }],
				"heading-m-sans": ["2.4rem", { lineHeight: "2.9rem" }],
				"heading-m-serif": ["2.4rem", { lineHeight: "3.1rem" }],
				"heading-m-mono": ["2.4rem", { lineHeight: "2.5rem" }],
				"heading-m-mobile-sans": ["1.8rem", { lineHeight: "2.4rem" }],
				"heading-m-mobile-serif": ["1.8rem", { lineHeight: "2.4rem" }],
				"heading-m-mobile-mono": ["1.8rem", { lineHeight: "2.4rem" }],
				"heading-s-sans": ["2rem", { lineHeight: "2.4rem" }],
				"heading-s-serif": ["2rem", { lineHeight: "2.6rem" }],
				"heading-s-mono": ["2rem", { lineHeight: "2.1rem" }],
				"heading-s-mobile-sans": ["1.6rem", { lineHeight: "1.9rem" }],
				"heading-s-mobile-serif": ["1.6rem", { lineHeight: "2rem" }],
				"heading-s-mobile-mono": ["1.6rem", { lineHeight: "1.7rem" }],
				"body-m-mobile-sans": ["1.5rem", { lineHeight: "2.4rem" }],
				"body-m-mobile-serif": ["1.5rem", { lineHeight: "2.4rem" }],
				"body-m-mobile-mono": ["1.5rem", { lineHeight: "2.4rem" }],
				"body-m-sans": ["1.8rem", { lineHeight: "2.4rem" }],
				"body-m-serif": ["1.8rem", { lineHeight: "2.4rem" }],
				"body-m-mono": ["1.8rem", { lineHeight: "2.4rem" }],
				"body-s-mobile-sans": ["1.4rem", { lineHeight: "2.4rem" }],
				"body-s-mobile-serif": ["1.4rem", { lineHeight: "2.4rem" }],
				"body-s-mobile-mono": ["1.4rem", { lineHeight: "2.4rem" }],
				"body-s-sans": ["1.4rem", { lineHeight: "1.5rem" }],
				"body-s-serif": ["1.4rem", { lineHeight: "1.8rem" }],
				"body-s-mono": ["1.4rem", { lineHeight: "2.4rem" }],
			},
			screens: {
				lg: "1440px",
			},
		},
	},
	plugins: [],
};
